modLoader="javafml"
loaderVersion="[44,)"
license="Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License"
issueTrackerURL="https://github.com/Povstalec/StargateJourney/issues"
[[mods]]
modId="sgjourney"
version="0.6.7"
displayName="Stargate Journey"
logoFile="sgjourney_large.png"
credits="TakeruDavis, Otwnt, Kranyolsu, Carter Addon Pack, diesieben07, TelepathicGrunt, SquidDev"
authors="Woldericz_Junior"
displayTest="MATCH_VERSION"

description='''
Stargate in Minecraft! And much more.
'''
[[dependencies.sgjourney]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sgjourney]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sgjourney]]
    modId="computercraft"
    mandatory=false
    versionRange="[1.103.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.sgjourney]]
    modId="stellarview"
    mandatory=false
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="CLIENT"
